feat/DLCL-877-arrow-navigation-in-list
dataloop-ai/components pull request #148
Opened 2023-04-12 13:58 UTC by vadim-popa-opentech

---------------------------------------------
| Q  | A |
| ------------- | ------------- |
| Related tickets | https://opentechdev.atlassian.net/browse/DLCL-877 |
| Vue2 |  Y |
| Vue3 |  Y |
| Storybook |  N |
| Tests |  N |
| Demo |  Y |

### Changelog

* New: The arrow navigation hook has created and implemented in DlMenuDemo

2023-04-13 12:59 UTC, fadiDL requested changes
The approach is good in general but it requires people to implement this behavior manually. 

Please explain to me how will this integrate with https://github.com/dataloop-ai/components/pull/133

if its supposed to tackle the same logic then please merge the PRs togehter and make sure to close the other one. 

please implement this functionality automatically for our internal components like DlSelect DlSearch DlSmartSearch ( suggestions )  DlDropdownButton

any component that has dropdown ( portal ) menu.


@prodan-eric @vadim-popa-opentech

2023-04-24 16:22 UTC, fadiDL commented
@vadim-popa-opentech you didnt answer me yet about the duplicated branch. what should we do with these. please sync with @prodan-eric before we can continue with this and close the non relevant branches/PRs

2023-04-25 07:37 UTC, vadim-popa-opentech commented
> @vadim-popa-opentech you didnt answer me yet about the duplicated branch. what should we do with these. please sync with @prodan-eric before we can continue with this and close the non relevant branches/PRs

@fadiDL  the https://github.com/dataloop-ai/components/pull/133 branch was closed

2023-04-25 11:12 UTC, fadiDL approved these changes

2023-04-25 11:12 UTC, merged