Thumbnail Gallery Component
dataloop-ai/components pull request #168
Opened 2023-04-18 08:33 UTC by prodan-eric

https://opentechdev.atlassian.net/jira/software/projects/DLCL/boards/17?assignee=637212f85fc160544e16fa5f&selectedIssue=DLCL-789

2023-05-18 13:31 UTC, fadiDL requested changes

2023-05-18 13:31 UTC, fadiDL commented on src/stories/DlThumbnailGallery.stories.js
Please refactor this to the new style of stories and documentation with jsdoc inside the component itself.
checkout `DlEllipsis.stories.ts` for reference and `DlEllipsis.vue` for the doc

2023-05-24 13:44 UTC, prodan-eric commented on src/components/compound/DlThumbnailGallery/DlThumbnailGallery.vue
Clicking an image directly updates the v-model, so the "selected" event would be equivalent to listening to @update:modelValue from outside

2023-05-24 13:49 UTC, prodan-eric commented on src/components/compound/DlThumbnailGallery/index.ts
> +export type { DlThumbnail }
I removed it and added it separately in the demo file for demo purpose

2023-05-28 10:41 UTC, fadiDL requested changes

2023-05-28 10:41 UTC, fadiDL commented on src/demos/index.ts
> +export const demoState = {
We removed demoState in change for a export default a long time ago. please revert this to match.

2023-05-28 14:29 UTC, fadiDL commented on src/demos/index.ts
> +export const demoState = {
I solved it

2023-05-28 14:34 UTC, fadiDL commented on src/components/essential/DlIcon/DlIcon.vue
This is a merge conflict. this code should not be reverted!

2023-05-28 14:34 UTC, fadiDL commented on src/components/essential/DlIcon/DlIcon.vue
fixing conflicts

2023-05-28 14:35 UTC, fadiDL approved these changes

2023-05-28 14:36 UTC, fadiDL commented
@prodan-eric please pay attention in the future to incorrect merge conflict resolutions. this branch contained changess that revert/ignore fixes we already introduced.

2023-05-28 14:40 UTC, merged