DlTabs -> fix dl-tab fontSize/iconSize
dataloop-ai/components pull request #303
Opened 2023-05-23 11:42 UTC by SorinOpt

**Thank you for your contribution to the repo. Before submitting this PR, please make sure:**
- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved terminology
- [ ] You have added unit tests
- [ ] You have updated documentation
- [ ] You have tested your changes

**Please provide a description of the changes proposed in the pull request and reference any related issues in the repository.**

**Please indicate if this PR contains:**
- [x] A bug fix
- [ ] A feature request
- [ ] Breaking changes
- [x] An enhancement

2023-05-23 12:45 UTC, fadiDL requested changes

2023-05-23 13:35 UTC, SorinOpt commented on src/components/compound/DlTabs/DlTabs.vue
> +        iconSize: { type: String, default: '16px' }
ok, but if the font size can be customized, the icon size will remain the same.

2023-05-23 14:14 UTC, SorinOpt commented on src/components/compound/DlTabs/DlTabs.vue
> +        iconSize: { type: String, default: '16px' }
> Please remove this prop as it seems like its not needed. we always want the icon to be -2 of the fontsize as per description of the issue

fixed

2023-05-24 09:21 UTC, fadiDL approved these changes

2023-05-24 09:22 UTC, fadiDL commented on src/components/compound/DlTabs/DlTabs.vue
> +        iconSize: { type: String, default: '16px' }
@SorinOpt i meant extrapolate the iconsize from the fontsize. ill handle it

2023-05-24 09:37 UTC, merged