Feat/dlcl 776 empty state
dataloop-ai/components pull request #345
Opened 2023-05-30 12:45 UTC by SorinOpt

**Thank you for your contribution to the repo. Before submitting this PR, please make sure:**
- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved terminology
- [ ] You have added unit tests
- [ ] You have updated documentation
- [ ] You have tested your changes

**Please provide a description of the changes proposed in the pull request and reference any related issues in the repository.**

**Please indicate if this PR contains:**
- [ ] A bug fix
- [ ] A feature request
- [ ] Breaking changes
- [ ] An enhancement

2023-05-31 13:07 UTC, fadiDL requested changes

2023-05-31 13:07 UTC, fadiDL commented on src/demos/assets/agenda.svg
@SorinOpt where di you get this svg from ? seems like it needs to be in our DlIcons repo

2023-05-31 13:07 UTC, fadiDL commented on tests/DlEmptyState.spec.ts
Need to rewrite this to align with other tests we have in the library.

2023-06-01 08:22 UTC, SorinOpt commented on src/demos/assets/agenda.svg
how we can use dataloop icons as a background image?

2023-06-01 10:27 UTC, fadiDL commented on src/demos/assets/agenda.svg
@SorinOpt  You can acess the svg files from the icons repository
or using the git link itself  see in the dl-icon how we handle loading an svg file from dataloop

2023-06-05 08:37 UTC, fadiDL approved these changes

2023-06-05 08:43 UTC, merged