DLCL-482-dl-td-transform-prop
dataloop-ai/components pull request #513
Opened 2023-07-27 13:30 UTC by vadim-popa-opentech

The prop transform has added for DlTd component

2023-07-27 16:02 UTC, fadiDL approved these changes

2023-07-27 16:03 UTC, fadiDL requested changes

2023-07-27 16:03 UTC, fadiDL commented on src/components/compound/DlTable/components/DlTd.vue
@vadim-popa-opentech can this be passed by column options and not just explictly to the dl-td?

2023-07-28 12:19 UTC, vadim-popa-opentech commented on src/components/compound/DlTable/components/DlTd.vue
the textTransform has passed by column options

2023-07-28 13:38 UTC, fadiDL approved these changes

2023-07-28 13:39 UTC, merged