Feat/tree drag
dataloop-ai/components pull request #624
Opened 2023-10-12 16:33 UTC by SorinOpt

**Thank you for your contribution to the repo. Before submitting this PR, please make sure:**
- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved terminology
- [ ] You have added unit tests
- [ ] You have updated documentation
- [ ] You have tested your changes

**Please provide a description of the changes proposed in the pull request and reference any related issues in the repository.**

**Please indicate if this PR contains:**
- [ ] A bug fix
- [ ] A feature request
- [ ] Breaking changes
- [ ] An enhancement

2023-10-15 08:33 UTC, fadiDL requested changes
@SorinOpt @prodan-eric Great job on this overall im very impressed with the work you did here especially on the tree table and making everything work with the table component

Once tests are available i will dig deeper into the table component itself for more closer review

2023-10-15 08:33 UTC, fadiDL commented on src/components/compound/DlTreeTable/utils/treeTableRowSelection.ts
> +        console.log('updates')
remove log please

2023-10-15 08:33 UTC, fadiDL commented on src/components/compound/DlTreeTable/utils/treeTableRowSelection.ts
> +        console.log({ added })
remove log please

2023-10-15 08:33 UTC, fadiDL commented on src/components/compound/DlTreeTable/views/DlTrTreeView.vue
> +    <!-- v-show="row.isExpandedParent || row.level === 1" -->
remove comment

2023-10-15 08:33 UTC, fadiDL commented on src/components/compound/DlTreeTable/views/DlTrTreeView.vue
> +            context.emit('rowDblClick', evt, row, rowIndex)
can we rename it back to `rowDoubleClick` please

2023-10-15 08:33 UTC, fadiDL commented on src/components/compound/DlTreeTable/views/DlTrTreeView.vue
> +                // styles = styles
comments

2023-10-15 08:33 UTC, fadiDL commented on src/components/compound/DlTreeTable/views/DlTrTreeView.vue
> +                // console.log(val)
also here

2023-10-15 08:33 UTC, fadiDL commented on src/components/compound/DlTreeTable/views/DlTrTreeView.vue
> +            log: console.log,
why is this here ?

2023-10-16 08:20 UTC, prodan-eric commented on src/components/compound/DlTable/DlTable.vue
>          Object.assign(vm.proxy, {
This is a way to expose these specific functions in separaate hooks and functions (where we pass the vm). For example the draggable-table.ts file uses the vm to update the data on drag

2023-10-16 08:22 UTC, prodan-eric commented on src/components/compound/DlTable/components/DlTd.vue
> +        <slot />
It means the content passed as slot would show both in the td itself and in the tooltip (only in case of ellipsis)

2023-10-17 14:05 UTC, fadiDL submitted a review, later dismissed

2023-10-17 14:07 UTC, fadiDL approved these changes

2023-10-17 14:13 UTC, merged