chore: add empty state to dl-scatter-chart component
dataloop-ai/components pull request #712
Opened 2023-11-07 06:51 UTC by jabezX

**Thank you for your contribution to the repo. Before submitting this PR, please make sure:**
- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved terminology
- [ ] You have added unit tests
- [ ] You have updated documentation
- [ ] You have tested your changes

**Please provide a description of the changes proposed in the pull request and reference any related issues in the repository.**

**Please indicate if this PR contains:**
- [ ] A bug fix
- [ ] A feature request
- [ ] Breaking changes
- [ ] An enhancement

2023-11-13 16:26 UTC, RotemDl requested changes
Looks good! Can you add a test?

2023-11-15 16:47 UTC, jabezX commented
Sure. I'll update accordingly.

2023-11-20 16:59 UTC, fadiDL approved these changes

2023-11-20 16:59 UTC, fadiDL commented
Merging without tests for now

2023-11-20 16:59 UTC, merged