Sticky columns & Fit columns
dataloop-ai/components pull request #724
Opened 2023-11-08 09:40 UTC by SorinOpt

Added new string prop called "stickyColumns" that can have the values "first", "last" or "both"
Added new boolean prop called "fitAllColumns" that will make the columns shrink to fit to the table's size
Added demos for both features
Reorganized code inside the table-columns.ts file

2023-11-16 14:38 UTC, fadiDL commented
@SorinOpt how would this react ? 
![image](https://github.com/dataloop-ai/components/assets/99925584/ea129b00-0381-46d0-b7d6-2455964d8052)

For some reason the table now is not fit in the original by default... lets have a call soon to go over this PR

2023-11-21 09:40 UTC, SorinOpt commented
> @SorinOpt how would this react ? ![image](https://user-images.githubusercontent.com/99925584/283488665-ea129b00-0381-46d0-b7d6-2455964d8052.png)
> 
> For some reason the table now is not fit in the original by default... lets have a call soon to go over this PR

I believe this is fixable by making the prop be true by default ( I also reversed the demo  a bit). Let me know if this is what you mean

2023-11-23 12:33 UTC, fadiDL requested changes
One last issue is when there are too many columns to fit we dont have ellipsis on the th

![image](https://github.com/dataloop-ai/components/assets/99925584/3cd8a9b1-a7a6-4067-acac-c2134cc4056a)

2023-11-23 16:16 UTC, fadiDL approved these changes

2023-11-23 16:17 UTC, merged