adding the variable value in case of props
dataloop-ai/components pull request #891
Opened 2024-03-04 14:27 UTC by gauravs0124

**Thank you for your contribution to the repo. Before submitting this PR, please make sure:**
- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved terminology
- [ ] You have added unit tests
- [ ] You have updated documentation
- [ ] You have tested your changes

**Please provide a description of the changes proposed in the pull request and reference any related issues in the repository.**

**Please indicate if this PR contains:**
- [ ] A bug fix
- [ ] A feature request
- [ ] Breaking changes
- [ ] An enhancement

2024-03-04 14:34 UTC, fadiDL requested changes

2024-03-04 14:34 UTC, fadiDL commented on src/components/compound/DlDropdownButton/DlDropdownButton.vue
> +            default: ''
default it to null please

2024-03-05 11:38 UTC, guyDataloop submitted a review, later dismissed

2024-03-05 13:36 UTC, guyDataloop approved these changes

2024-03-05 13:42 UTC, merged