DAT-68229  Highlight row on mount
dataloop-ai/components pull request #915
Opened 2024-05-01 08:03 UTC by yogesh0325

Hi @fadiDL @makc-dataloop @guyDataloop 
Please review the code.

- DAT-68229  Highlight row on mount

**Thank you for your contribution to the repo. Before submitting this PR, please make sure:**
- [ ] Your code builds clean without any errors or warnings
- [ ] You are using approved terminology
- [ ] You have added unit tests
- [ ] You have updated documentation
- [ ] You have tested your changes

**Please provide a description of the changes proposed in the pull request and reference any related issues in the repository.**

**Please indicate if this PR contains:**
- [ ] A bug fix
- [ ] A feature request
- [ ] Breaking changes
- [ ] An enhancement

2024-05-01 08:25 UTC, makc-dataloop commented
@fadiDL @guyDataloop context: \<dl-tree-table> component used by label picker has its own selection mechanism that presents checkboxes, so back in DAT-67499 PR https://github.com/dataloop-ai/components/pull/901 I toggled \<tr> class instead, however it only worked on click. here Yogesh does the same but via data attribute.

2024-05-02 12:12 UTC, guyDataloop requested changes

2024-05-02 12:12 UTC, guyDataloop commented on src/components/blocks/DlLabelPicker/DlLabelPicker.vue
> +                    `[data-label-picker-identifier="${items.value?.[0]?.identifier}"]`
Check that `items.value?.[0]?.identifier` exists first, so we don't update the `selected` class when the identifier is not defined

2024-05-02 13:28 UTC, guyDataloop approved these changes

2024-05-02 13:33 UTC, merged